# Template of CSV file, to be filled by operator-sdk generate bundle / make update.
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: aws-efs-operator.v4.8.0
  namespace: openshift-operators
  annotations:
    capabilities: Full Lifecycle
    categories: "Storage"
    certified: "false"
    description: Management of AWS EFS read-write-many mounts.
    containerImage: quay.io/app-sre/aws-efs-operator:latest
    createdAt: "2020-04-18T21:43:33Z"
    support: Red Hat
    repository: https://github.com/openshift/local-storage-operator

spec:
  displayName: AWS EFS CSI Driver Operator
  description: Management of AWS EFS CSI driver and read-write-many mounts.
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  - EFS
  version: 4.8.0
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
