apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    categories: Storage
    certified: "false"
    containerImage: quay.io/app-sre/aws-efs-operator:latest
    createdAt: "2020-04-18T21:43:33Z"
    description: Management of AWS EFS read-write-many mounts.
    operators.operatorframework.io/builder: operator-sdk-v1.4.0+git
    operators.operatorframework.io/project_layout: unknown
    repository: https://github.com/openshift/local-storage-operator
    support: Red Hat
  name: aws-efs-operator.v4.8.0
  namespace: openshift-operators
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: SharedVolume
      name: sharedvolumes.aws-efs.managed.openshift.io
      version: v1alpha1
  description: Management of AWS EFS CSI driver and read-write-many mounts.
  displayName: AWS EFS CSI Driver Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumes
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - aws-efs-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - aws-efs.managed.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          - storageclasses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - list
          - watch
        serviceAccountName: aws-efs-operator
      deployments:
      - name: aws-efs-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: aws-efs-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: aws-efs-operator
            spec:
              containers:
              - args:
                - start
                - -v=5
                env:
                - name: DRIVER_IMAGE
                  value: amazon/aws-efs-csi-driver:v1.1.1
                - name: NODE_DRIVER_REGISTRAR_IMAGE
                  value: quay.io/openshift/origin-csi-node-driver-registrar:latest
                - name: LIVENESS_PROBE_IMAGE
                  value: quay.io/openshift/origin-csi-livenessprobe:latest
                image: quay.io/jsafrane/efs:operator
                imagePullPolicy: IfNotPresent
                name: aws-efs-operator
                resources: {}
              serviceAccountName: aws-efs-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  - EFS
  maturity: alpha
  provider:
    name: Red Hat, Inc
  version: 4.8.0
